import { StyleSheet } from "react-native";
export default styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1E1E1E",
    alignItems: "center",
    justifyContent: "center",
  },
  banar: {
    width: "100%",
    height: 350,
    alignItems: "center",
    justifyContent: "center",
  },
  banarImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  banarText: {
    color: "white",
    fontSize: 26,
    fontWeight: "bold",
    marginTop: "auto",
    marginHorizontal: "auto",
    marginBottom: 10,
  },
  banarBtn: {
    position: "absolute",
    bottom: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    width: "100%",
    padding: 10,
    borderRadius: 10,
  },
  banarPlayBtn: {
    flexDirection: "row",
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    padding: 10,
    marginRight: 10,
    width: "40%",
  },
  banarPlayBtnText: {
    color: "black",
    fontSize: 18,
    fontWeight: "bold",
  },
  banarMyListBtnText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
  },
  banarListBtn: {
    flexDirection: "row",
    backgroundColor: "#2b2b2d",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    padding: 10,
    width: "40%",
  },

  textHeader: {
    color: "white",
    fontSize: 24,
    fontWeight: "bold",
    margin: 10,
  },
  footer: {
    width: "100%",
    height: 100,
    marginTop: 20,
    backgroundColor: "#1E1E1E",
    alignItems: "center",
    justifyContent: "center",
  },
  footerText: {
    color: "white",
    padding: 20,
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 18,
  },
  footerBtn: {
    backgroundColor: "#c13f32",
    borderRadius: 10,
    padding: 10,
    marginBottom: 30,
  },
  footerBtnText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
  },
});
